# Generated by Django 3.0.7 on 2020-07-04 03:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=150)),
                ('Registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.FloatField(max_length=8)),
                ('Desc', models.TextField(blank=True, max_length=300, null=True)),
                ('towersNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Latitude', models.FloatField(max_length=10, unique=True)),
                ('Longitude', models.FloatField(max_length=10, unique=True)),
                ('Area', models.FloatField(max_length=8)),
                ('Desc', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Proof', models.FileField(upload_to='images')),
                ('Birthdate', models.DateField()),
                ('jobDesc', models.TextField(max_length=200)),
                ('Mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')])),
                ('DSL', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='DSL Number must be entered exactly 10 digits.', regex='^(\\d{10})$')])),
                ('Avatar', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Existence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], default='enter', max_length=5)),
                ('Timing', models.DateTimeField(default=django.utils.timezone.now)),
                ('NID', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.IntegerField()),
                ('Proof', models.FileField(upload_to='images')),
                ('Birthdate', models.DateField()),
                ('Mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')])),
                ('DSL', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='DSL Number must be entered exactly 10 digits.', regex='^(\\d{10})$')])),
                ('Avatar', models.ImageField(upload_to='images')),
                ('isOwner', models.BooleanField(default=True)),
                ('Notes', models.TextField(blank=True, max_length=200, null=True)),
                ('Papers', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ownershipStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='ownershipTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField()),
                ('Paid', models.FloatField()),
                ('serialTransaction', models.FloatField()),
                ('proofTransaction', models.FileField(upload_to='images')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Admin')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=250)),
                ('Type', models.CharField(choices=[('طلب', 'طلب'), ('شكوي', 'شكوي')], default='طلب', max_length=9)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Replied', models.BooleanField(blank=True, default=False, null=True)),
                ('Action', models.TextField(blank=True, max_length=250, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Area', models.FloatField(max_length=8)),
                ('flatsNumber', models.IntegerField(null=True)),
                ('Cost', models.FloatField(max_length=8)),
                ('Notes', models.TextField(max_length=200, null=True)),
                ('Papers', models.FileField(null=True, upload_to='images')),
                ('floorsNumber', models.IntegerField()),
                ('storesNumber', models.IntegerField()),
                ('Type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=12)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_tower', to='emp.Block')),
                ('owners', models.ManyToManyField(through='emp.ownershipTower', to='emp.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=300)),
                ('Type', models.CharField(choices=[('shop', 'Shop'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('gym', 'Gym')], default='shop', max_length=12)),
                ('owners', models.ManyToManyField(through='emp.ownershipStore', to='emp.Owner')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_store', to='emp.Tower')),
            ],
        ),
        migrations.AddField(
            model_name='ownershiptower',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Tower'),
        ),
        migrations.AddField(
            model_name='ownershipstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Store'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Installement', models.CharField(choices=[('تقسيط', 'تقسيط'), ('كاش', 'كاش')], default='تقسيط', max_length=12)),
                ('Cost', models.FloatField(max_length=8)),
                ('minPayment', models.FloatField(blank=True, max_length=8, null=True)),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('Avatar', models.FileField(blank=True, null=True, upload_to='images')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_owner', to='emp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Avatar', models.FileField(blank=True, null=True, upload_to='images')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_owner', to='emp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorNumber', models.IntegerField()),
                ('Area', models.FloatField(max_length=8)),
                ('Desc', models.TextField(blank=True, max_length=300, null=True)),
                ('Inhabited', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_flat', to='emp.Owner')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_flat', to='emp.Tower')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_block', to='emp.Compound'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Birthdate', models.DateField()),
                ('Relationship', models.CharField(choices=[('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('cousin', 'Cousin'), ('husband', 'Husband')], default='wife', max_length=9)),
                ('Proof', models.FileField(upload_to='images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_family', to='emp.Owner')),
            ],
            options={
                'unique_together': {('owner', 'Name')},
            },
        ),
    ]
