# Generated by Django 3.0.7 on 2020-07-11 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('NID', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('Username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=150)),
                ('Registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True, unique=True)),
                ('Area', models.FloatField(max_length=8)),
                ('Desc', models.TextField(blank=True, max_length=300, null=True)),
                ('towersNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Number', models.IntegerField(null=True, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Latitude', models.FloatField(max_length=10, unique=True)),
                ('Longitude', models.FloatField(max_length=10, unique=True)),
                ('Area', models.FloatField(max_length=8)),
                ('Desc', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Proof', models.FileField(upload_to='images')),
                ('Birthdate', models.DateField()),
                ('jobDesc', models.TextField(max_length=200)),
                ('Mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')])),
                ('DSL', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='DSL Number must be entered exactly 10 digits.', regex='^(\\d{10})$')])),
                ('Avatar', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Existence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], default='enter', max_length=5)),
                ('Timing', models.DateTimeField(default=django.utils.timezone.now)),
                ('NID', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Installement', models.CharField(choices=[('تقسيط', 'تقسيط'), ('كاش', 'كاش')], default='تقسيط', max_length=12)),
                ('Cost', models.FloatField(max_length=8)),
                ('minPayment', models.FloatField(blank=True, max_length=8, null=True)),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('Avatar', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('Name', models.CharField(max_length=200)),
                ('Proof', models.FileField(null=True, upload_to='images')),
                ('Birthdate', models.DateField()),
                ('Mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')])),
                ('DSL', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='DSL Number must be entered exactly 10 digits.', regex='^(\\d{10})$')])),
                ('Avatar', models.ImageField(null=True, upload_to='images')),
                ('Notes', models.TextField(blank=True, max_length=200, null=True)),
                ('Type', models.CharField(choices=[('own', 'own'), ('rent', 'rent')], default='own', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ownershipStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=250)),
                ('Type', models.CharField(choices=[('request', 'request'), ('complaint', 'complaint')], default='request', max_length=9)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Replied', models.BooleanField(blank=True, default=False, null=True)),
                ('Action', models.TextField(blank=True, max_length=250, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Area', models.FloatField(max_length=8)),
                ('flatsNumber', models.IntegerField(null=True)),
                ('Cost', models.FloatField(max_length=8)),
                ('Notes', models.TextField(max_length=200, null=True)),
                ('floorsNumber', models.IntegerField()),
                ('storesNumber', models.IntegerField()),
                ('Number', models.IntegerField(default=2)),
                ('Type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=12)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_tower', to='emp.Block')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_tower', to='emp.Owner')),
            ],
            options={
                'unique_together': {('block', 'Number')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True, unique=True)),
                ('floorNumber', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=300)),
                ('Type', models.CharField(choices=[('shop', 'shop'), ('restaurant', 'restaurant'), ('cafe', 'cafe'), ('gym', 'gym'), ('mall', 'mall')], default='shop', max_length=12)),
                ('owners', models.ManyToManyField(through='emp.ownershipStore', to='emp.Owner')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_store', to='emp.Tower')),
            ],
            options={
                'unique_together': {('tower', 'Number')},
            },
        ),
        migrations.AddField(
            model_name='ownershipstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Store'),
        ),
        migrations.AddField(
            model_name='block',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_block', to='emp.Compound'),
        ),
        migrations.AlterUniqueTogether(
            name='ownershipstore',
            unique_together={('owner', 'store')},
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=2, unique=True)),
                ('floorNumber', models.IntegerField()),
                ('Area', models.FloatField(max_length=8)),
                ('Inhabited', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_flat', to='emp.Owner')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_flat', to='emp.Tower')),
            ],
            options={
                'unique_together': {('Number', 'tower')},
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Birthdate', models.DateField()),
                ('Relationship', models.CharField(choices=[('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('cousin', 'Cousin'), ('husband', 'Husband'), ('friend', 'friend'), ('father', 'father'), ('mother', 'mother'), ('uncle', 'uncle'), ('aunt', 'aunt'), ('brother', 'brother'), ('sister', 'sister')], default='wife', max_length=9)),
                ('Proof', models.FileField(null=True, upload_to='images')),
                ('NID', models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be entered exactly 14 digits.', regex='^(\\d{14})$')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_family', to='emp.Owner')),
            ],
            options={
                'unique_together': {('owner', 'NID')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('compound', 'Number')},
        ),
    ]
