# Generated by Django 3.0.7 on 2020-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_remove_owner_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='Papers',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
