# Generated by Django 3.0.7 on 2020-07-11 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20200711_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
