# Generated by Django 3.0.7 on 2020-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200711_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Cost',
            field=models.FloatField(max_length=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='minPayment',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
    ]
