# Generated by Django 3.0.7 on 2020-07-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200705_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='Papers',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
