# Generated by Django 3.0.7 on 2020-07-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20200705_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='Papers',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
