# Generated by Django 3.0.7 on 2020-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20200711_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Cost',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Installement',
            field=models.CharField(choices=[('install', 'install'), ('cash', 'cash')], default='install', max_length=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='minPayment',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
