# Generated by Django 3.0.7 on 2020-07-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_auto_20200705_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='Papers',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
