# Generated by Django 3.0.7 on 2020-07-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20200705_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='Papers',
        ),
    ]
