# Generated by Django 3.0.7 on 2020-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_remove_tower_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='Papers',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
