# Generated by Django 3.0.7 on 2020-07-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_tower_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Number',
            field=models.IntegerField(default=2),
        ),
    ]
