# Generated by Django 3.0.7 on 2020-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_remove_flat_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='Number',
            field=models.IntegerField(default=2),
        ),
    ]
