# Generated by Django 3.0.7 on 2020-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_tower_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='Number',
            field=models.IntegerField(default=2),
        ),
    ]
