# Generated by Django 3.0.7 on 2020-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_remove_owner_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='isOwner',
        ),
        migrations.AddField(
            model_name='owner',
            name='Type',
            field=models.CharField(choices=[('own', 'own'), ('rent', 'rent')], default='own', max_length=12),
        ),
    ]
