# Generated by Django 3.0.7 on 2020-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_auto_20200705_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Avatar',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='Proof',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
