# Generated by Django 3.0.7 on 2020-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0018_auto_20200705_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='Relationship',
            field=models.CharField(choices=[('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('cousin', 'Cousin'), ('husband', 'Husband'), ('friend', 'friend'), ('father', 'father'), ('mother', 'mother'), ('uncle', 'uncle'), ('aunt', 'aunt'), ('brother', 'brother'), ('sister', 'sister')], default='wife', max_length=9),
        ),
    ]
