# Generated by Django 3.0.7 on 2020-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0019_auto_20200705_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
