# Generated by Django 3.0.7 on 2020-07-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0020_auto_20200706_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_family', to='emp.Owner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='Type',
            field=models.CharField(choices=[('shop', 'Shop'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('gym', 'Gym'), ('mall', 'mall')], default='shop', max_length=12),
        ),
    ]
