# Generated by Django 3.0.7 on 2020-07-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0021_auto_20200706_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Type',
            field=models.CharField(choices=[('shop', 'shop'), ('restaurant', 'restaurant'), ('cafe', 'cafe'), ('gym', 'gym'), ('mall', 'mall')], default='shop', max_length=12),
        ),
    ]
