# Generated by Django 3.0.7 on 2020-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0022_auto_20200706_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='Number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
