# Generated by Django 3.0.7 on 2020-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0025_auto_20200708_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='Number',
            field=models.IntegerField(default=2, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
