# Generated by Django 3.0.7 on 2020-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0028_auto_20200708_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershiptower',
            name='Paid',
        ),
        migrations.RemoveField(
            model_name='ownershiptower',
            name='Total',
        ),
        migrations.RemoveField(
            model_name='ownershiptower',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='ownershiptower',
            name='proofTransaction',
        ),
        migrations.RemoveField(
            model_name='ownershiptower',
            name='serialTransaction',
        ),
        migrations.AlterField(
            model_name='tower',
            name='Number',
            field=models.IntegerField(default=2),
        ),
    ]
