# Generated by Django 3.0.7 on 2020-07-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0029_auto_20200708_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='owners',
        ),
        migrations.AddField(
            model_name='tower',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_tower', to='emp.Owner'),
        ),
        migrations.DeleteModel(
            name='ownershipTower',
        ),
    ]
