# Generated by Django 3.0.7 on 2020-07-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0031_auto_20200710_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='floorNumber',
            field=models.IntegerField(null=True),
        ),
    ]
