# Generated by Django 3.0.7 on 2020-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0034_auto_20200711_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
